### ISSUE TITLE
Connection refused: localhost/127.0.0.1:25565  > seem to show any life signs after ~30 seconds, meaning he didn't join/quit correctly! Aborting!

### ISSUE THREAD

**Issue by Dcnigma** [marlester-dev/ReallyFakePlayers#12]
Hey got a issue, been using the older plugin > ReallyFakePlayers-2.0.0.4-1.20.1.jar for a long time, 
even when ReallyFakePlayers-2.0.0.5-1.20.1.jar came out because it gave me errors.

I updated my server to 1.20.4 and now i am running the latest release > [ReallyFakePlayers-3.0.4.jar]

Can't see any other errors then > LibertyBans
<details><summary>LibertyBans error</summary>
<p>
`[17:15:00 WARN]: [LibertyBans] *******************************************
We have detected bugs on your server which threaten your server's stability.
LibertyBans will continue to operate unaffected, but we strongly suggest you fix these bugs.

These bugs are (most likely) due to other plugins' mistakes. Each of the following plugins has shaded a library but did not relocate it. You should report each bug to the plugin author.

Plugin Name | Library Name | Class Detected
----------------------------------------------
Plugin 'ReallyFakePlayers 3.0.4' | Jakarta-Inject | jakarta.inject.Provider

Note for advanced users: Understanding the consequences, you can minimize this warning by setting the system property libertybans.relocationbug.disablecheck to 'true'
</p>
</details> 

But then again LibertyBans gave me more errors like this in the past for other plugins 
I getting some errors when i try to run it...
<details><summary>Details Error i get when i add a player</summary>
<p>

`17:20:24 WARN]: [ReallyFakePlayers] Fake player Clevon disconnected with an error!
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:25565
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:673) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973) ~[?:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[17:20:54 ERROR]: [ReallyFakePlayers] Fake player Clevon doesn't seem to show any life signs after ~30 seconds, meaning he didn't join/quit correctly! Aborting!
</p>
</details> 

Disabled LibertyBans but that didn't help.

I am running a lot of plugins.
<details><summary>plugins details</summary>
<p>
`Autorank.jar
AxSmithing-1.2-all.jar
BetterKeepInventory-1.0.2.jar
BetterRTP.jar
CMILib.jar
ChatInjector.jar
ChunkSpawnerLimiter.jar
Chunky.jar
CommandAPI.jar
CommandPrompter.jar
CommandWhitelist.jar
CoreProtect.jar
CrazyCrates.jar
DecentHolograms.jar
Deluxe Mentions.jar
DeluxeCommands.jar
DeluxeHub.jar
DeluxeMenus.jar
DeluxeTags.jar
DragonDropElytra.jar
Dynmap-3.6-spigot.jar
EconomyShopGUI.jar
EffectMaster.jar
EssentialsX.jar
ExecutableItems.jar
Expressions-Expansion-1.2.0.jar
FastChunkPregenerator.jar
GPFlags.jar
GSit.jar
GamerulesManager.jar
Geyser-Spigot.jar
GlobalLocalChat.jar
GriefPrevention.jar
HeadDB.jar
HeadDrop.jar
InfiniteVouchers.jar
InvSee++.jar
InvSee++_Clear.jar
InvSee++_Give.jar
InventoryRollbackPlus.jar
ItemDisplay-Expansion-1.0.0.jar
Item_Effects.jar
JoinCommands.jar
JoinPlugin.jar
LastLocation.jar
LibsDisguises.jar
LuckPerms-Bukkit.jar
MCKotlinPaper-1.4.0-k1.9.20.jar
MiniPlaceholders-Paper-2.2.3.jar
Morph.jar
Multiverse-Core.jar
Multiverse-Inventories.jar
Multiverse-Portals.jar
MyCommand.jar
Nameless-Plugin-Paper.jar
PlaceholderAPI.jar
PlayerWarps.jar
ProtocolLib.jar
PvPManager.jar
ReallyFakePlayers-3.0.4.jar
Referral.jar
ResourcePackPlugin.jar
SCore.jar
Shopkeepers.jar
ShulkerRespawner.jar
SilkSpawners_v2.jar
SkBee.jar
Skript.jar
Skulls.jar
SuperbVote.jar
TAB.jar
TradeSystem.jar
UltraCosmetics-3.4.2-RELEASE.jar
Vault-Expansion-1.0.0.jar
Vault.jar
VentureChat.jar
ViaBackwards.jar
ViaRewind.jar
ViaVersion.jar
VoidGen.jar
VotingPlugin.jar
WorldBorder.jar
WorldGuardExtraFlags.jar
WorldGuardRegionProtect.jar
clickaccept-0.5.jar
customcrafting-spigot.jar
eGlow.jar
floodgate-spigot.jar
grimac.jar
iShop.jar
infiniteannouncements.jar
item-nbt-api-plugin.jar
nuvotifier.jar
openaudiomc.jar
orebfuscator-plugin.jar
papervoucher.jar
pvparena.jar
skRayFall.jar
spark.jar
voicechat.jar
wolfyutils-spigot.jar
worldedit-bukkit.jar
worldguard-bukkit.jar`
</p>
</details> 

Any ideas? Update my jave version?
java 20.0.1 2023-04-18

and another crash
<details><summary>Crash Details</summary>
<p>

[17:45:24 ERROR]: ------------------------------
[17:45:24 ERROR]: Current Thread: Server thread
[17:45:24 ERROR]: 	PID: 36 | Suspended: false | Native: false | State: WAITING
[17:45:24 ERROR]: 	Stack:
[17:45:24 ERROR]: 		java.base@20.0.1/java.lang.Object.wait0(Native Method)
[17:45:24 ERROR]: 		java.base@20.0.1/java.lang.Object.wait(Object.java:366)
[17:45:24 ERROR]: 		java.base@20.0.1/java.lang.Object.wait(Object.java:339)
[17:45:24 ERROR]: 		io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:254)
[17:45:24 ERROR]: 		io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131)
[17:45:24 ERROR]: 		io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30)
[17:45:24 ERROR]: 		io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:405)
[17:45:24 ERROR]: 		io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:119)
[17:45:24 ERROR]: 		io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:30)
[17:45:24 ERROR]: 		ReallyFakePlayers-3.0.4.jar//com.github.steveice10.packetlib.tcp.TcpClientSession.connect(TcpClientSession.java:147)
[17:45:24 ERROR]: 		ReallyFakePlayers-3.0.4.jar//com.github.steveice10.packetlib.tcp.TcpSession.connect(TcpSession.java:64)
[17:45:24 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerImpl.join(FakePlayerImpl.java:110)
[17:45:24 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerManager.add(FakePlayerManager.java:56)
[17:45:24 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerManager.addNumber(FakePlayerManager.java:70)
[17:45:24 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.autojoin.AutoJoin$1.run(AutoJoin.java:55)
[17:45:24 ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:45:24 ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[17:45:24 ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1633)
[17:45:24 ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
[17:45:24 ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1512)
[17:45:24 ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[17:45:24 ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[17:45:24 ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$6444/0x0000000801ba4b30.run(Unknown Source)
[17:45:24 ERROR]: 		java.base@20.0.1/java.lang.Thread.runWith(Thread.java:1636)
[17:45:24 ERROR]: 		java.base@20.0.1/java.lang.Thread.run(Thread.java:1623)
[17:45:24 ERROR]: ------------------------------
[17:45:24 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[17:45:24 ERROR]: ------------------------------

</p>
</details>

**Comment by marlester-dev** [comment]
Hello, try to use java 17 instead and see. 
This error (Details Error i get when you add a player) is a little vague, do you have any more errors?
With LibertyBans it's a little more complicated, but I'll try to fix it.

**Comment by Dcnigma** [comment]
Hey I was able to test In java 17 but sadly it didn't help:

<details><summary>Some more logs:</summary>
<p>
[08:59:46 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-391 (MC: 1.20.4) ---
[08:59:46 ERROR]: The server has not responded for 10 seconds! Creating thread dump
[08:59:46 ERROR]: ------------------------------
[08:59:46 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[08:59:46 ERROR]: ------------------------------
[08:59:46 ERROR]: Current Thread: Server thread
[08:59:46 ERROR]: 	PID: 27 | Suspended: false | Native: false | State: WAITING
[08:59:46 ERROR]: 	Stack:
[08:59:46 ERROR]: 		java.base@17.0.2/java.lang.Object.wait(Native Method)
[08:59:46 ERROR]: 		java.base@17.0.2/java.lang.Object.wait(Object.java:338)
[08:59:46 ERROR]: 		io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:254)
[08:59:46 ERROR]: 		io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131)
[08:59:46 ERROR]: 		io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30)
[08:59:46 ERROR]: 		io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:405)
[08:59:46 ERROR]: 		io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:119)
[08:59:46 ERROR]: 		io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:30)
[08:59:46 ERROR]: 		ReallyFakePlayers-3.0.4.jar//com.github.steveice10.packetlib.tcp.TcpClientSession.connect(TcpClientSession.java:147)
[08:59:46 ERROR]: 		ReallyFakePlayers-3.0.4.jar//com.github.steveice10.packetlib.tcp.TcpSession.connect(TcpSession.java:64)
[08:59:46 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerImpl.join(FakePlayerImpl.java:110)
[08:59:46 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerManager.add(FakePlayerManager.java:56)
[08:59:46 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerManager.addNumber(FakePlayerManager.java:70)
[08:59:46 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.autojoin.AutoJoin$1.run(AutoJoin.java:55)
[08:59:46 ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[08:59:46 ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[08:59:46 ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1633)
[08:59:46 ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
[08:59:46 ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1512)
[08:59:46 ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[08:59:46 ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[08:59:46 ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$6428/0x00000008017d5f18.run(Unknown Source)
[08:59:46 ERROR]: 		java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
[08:59:46 ERROR]: ------------------------------
[08:59:46 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[08:59:46 ERROR]: ------------------------------
[08:59:51 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-391 (MC: 1.20.4) ---
[08:59:51 ERROR]: The server has not responded for 15 seconds! Creating thread dump
[08:59:51 ERROR]: ------------------------------
[08:59:51 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[08:59:51 ERROR]: ------------------------------
[08:59:51 ERROR]: Current Thread: Server thread
[08:59:51 ERROR]: 	PID: 27 | Suspended: false | Native: false | State: WAITING
[08:59:51 ERROR]: 	Stack:
[08:59:51 ERROR]: 		java.base@17.0.2/java.lang.Object.wait(Native Method)
[08:59:51 ERROR]: 		java.base@17.0.2/java.lang.Object.wait(Object.java:338)
[08:59:51 ERROR]: 		io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:254)
[08:59:51 ERROR]: 		io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131)
[08:59:51 ERROR]: 		io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30)
[08:59:51 ERROR]: 		io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:405)
[08:59:51 ERROR]: 		io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:119)
[08:59:51 ERROR]: 		io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:30)
[08:59:51 ERROR]: 		ReallyFakePlayers-3.0.4.jar//com.github.steveice10.packetlib.tcp.TcpClientSession.connect(TcpClientSession.java:147)
[08:59:51 ERROR]: 		ReallyFakePlayers-3.0.4.jar//com.github.steveice10.packetlib.tcp.TcpSession.connect(TcpSession.java:64)
[08:59:51 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerImpl.join(FakePlayerImpl.java:110)
[08:59:51 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerManager.add(FakePlayerManager.java:56)
[08:59:51 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerManager.addNumber(FakePlayerManager.java:70)
[08:59:51 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.autojoin.AutoJoin$1.run(AutoJoin.java:55)
[08:59:51 ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[08:59:51 ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[08:59:51 ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1633)
[08:59:51 ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
[08:59:51 ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1512)
[08:59:51 ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[08:59:51 ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[08:59:51 ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$6428/0x00000008017d5f18.run(Unknown Source)
[08:59:51 ERROR]: 		java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
[08:59:51 ERROR]: ------------------------------
[08:59:51 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[08:59:51 ERROR]: ------------------------------
[08:59:56 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-391 (MC: 1.20.4) ---
[08:59:56 ERROR]: The server has not responded for 20 seconds! Creating thread dump
[08:59:56 ERROR]: ------------------------------
[08:59:56 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[08:59:56 ERROR]: ------------------------------
[08:59:56 ERROR]: Current Thread: Server thread
[08:59:56 ERROR]: 	PID: 27 | Suspended: false | Native: false | State: WAITING
[08:59:56 ERROR]: 	Stack:
[08:59:56 ERROR]: 		java.base@17.0.2/java.lang.Object.wait(Native Method)
[08:59:56 ERROR]: 		java.base@17.0.2/java.lang.Object.wait(Object.java:338)
[08:59:56 ERROR]: 		io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:254)
[08:59:56 ERROR]: 		io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131)
[08:59:56 ERROR]: 		io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30)
[08:59:56 ERROR]: 		io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:405)
[08:59:56 ERROR]: 		io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:119)
[08:59:56 ERROR]: 		io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:30)
[08:59:56 ERROR]: 		ReallyFakePlayers-3.0.4.jar//com.github.steveice10.packetlib.tcp.TcpClientSession.connect(TcpClientSession.java:147)
[08:59:56 ERROR]: 		ReallyFakePlayers-3.0.4.jar//com.github.steveice10.packetlib.tcp.TcpSession.connect(TcpSession.java:64)
[08:59:56 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerImpl.join(FakePlayerImpl.java:110)
[08:59:56 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerManager.add(FakePlayerManager.java:56)
[08:59:56 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerManager.addNumber(FakePlayerManager.java:70)
[08:59:56 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.autojoin.AutoJoin$1.run(AutoJoin.java:55)
[08:59:56 ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[08:59:56 ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[08:59:56 ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1633)
[08:59:56 ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
[08:59:56 ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1512)
[08:59:56 ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[08:59:56 ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[08:59:56 ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$6428/0x00000008017d5f18.run(Unknown Source)
[08:59:56 ERROR]: 		java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
[08:59:56 ERROR]: ------------------------------
[08:59:56 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[08:59:56 ERROR]: ------------------------------
[09:00:01 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-391 (MC: 1.20.4) ---
[09:00:01 ERROR]: The server has not responded for 25 seconds! Creating thread dump
[09:00:01 ERROR]: ------------------------------
[09:00:01 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[09:00:01 ERROR]: ------------------------------
[09:00:01 ERROR]: Current Thread: Server thread
[09:00:01 ERROR]: 	PID: 27 | Suspended: false | Native: false | State: WAITING
[09:00:01 ERROR]: 	Stack:
[09:00:01 ERROR]: 		java.base@17.0.2/java.lang.Object.wait(Native Method)
[09:00:01 ERROR]: 		java.base@17.0.2/java.lang.Object.wait(Object.java:338)
[09:00:01 ERROR]: 		io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:254)
[09:00:01 ERROR]: 		io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131)
[09:00:01 ERROR]: 		io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30)
[09:00:01 ERROR]: 		io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:405)
[09:00:01 ERROR]: 		io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:119)
[09:00:01 ERROR]: 		io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:30)
[09:00:01 ERROR]: 		ReallyFakePlayers-3.0.4.jar//com.github.steveice10.packetlib.tcp.TcpClientSession.connect(TcpClientSession.java:147)
[09:00:01 ERROR]: 		ReallyFakePlayers-3.0.4.jar//com.github.steveice10.packetlib.tcp.TcpSession.connect(TcpSession.java:64)
[09:00:01 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerImpl.join(FakePlayerImpl.java:110)
[09:00:01 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerManager.add(FakePlayerManager.java:56)
[09:00:01 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerManager.addNumber(FakePlayerManager.java:70)
[09:00:01 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.autojoin.AutoJoin$1.run(AutoJoin.java:55)
[09:00:01 ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[09:00:01 ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[09:00:01 ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1633)
[09:00:01 ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
[09:00:01 ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1512)
[09:00:01 ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[09:00:01 ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[09:00:01 ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$6428/0x00000008017d5f18.run(Unknown Source)
[09:00:01 ERROR]: 		java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
[09:00:01 ERROR]: ------------------------------
[09:00:01 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[09:00:01 ERROR]: ------------------------------
[09:00:05 WARN]: [spark] Timed out waiting for world statistics
[09:00:06 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-391 (MC: 1.20.4) ---
[09:00:06 ERROR]: The server has not responded for 30 seconds! Creating thread dump
[09:00:06 ERROR]: ------------------------------
[09:00:06 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[09:00:06 ERROR]: ------------------------------
[09:00:06 ERROR]: Current Thread: Server thread
[09:00:06 ERROR]: 	PID: 27 | Suspended: false | Native: false | State: WAITING
[09:00:06 ERROR]: 	Stack:
[09:00:06 ERROR]: 		java.base@17.0.2/java.lang.Object.wait(Native Method)
[09:00:06 ERROR]: 		java.base@17.0.2/java.lang.Object.wait(Object.java:338)
[09:00:06 ERROR]: 		io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:254)
[09:00:06 ERROR]: 		io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131)
[09:00:06 ERROR]: 		io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30)
[09:00:06 ERROR]: 		io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:405)
[09:00:06 ERROR]: 		io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:119)
[09:00:06 ERROR]: 		io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:30)
[09:00:06 ERROR]: 		ReallyFakePlayers-3.0.4.jar//com.github.steveice10.packetlib.tcp.TcpClientSession.connect(TcpClientSession.java:147)
[09:00:06 ERROR]: 		ReallyFakePlayers-3.0.4.jar//com.github.steveice10.packetlib.tcp.TcpSession.connect(TcpSession.java:64)
[09:00:06 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerImpl.join(FakePlayerImpl.java:110)
[09:00:06 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerManager.add(FakePlayerManager.java:56)
[09:00:06 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.fakeplayers.FakePlayerManager.addNumber(FakePlayerManager.java:70)
[09:00:06 ERROR]: 		ReallyFakePlayers-3.0.4.jar//me.marlester.rfp.autojoin.AutoJoin$1.run(AutoJoin.java:55)
[09:00:06 ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[09:00:06 ERROR]: 		org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[09:00:06 ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1633)
[09:00:06 ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
[09:00:06 ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1512)
[09:00:06 ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[09:00:06 ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[09:00:06 ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$6428/0x00000008017d5f18.run(Unknown Source)
[09:00:06 ERROR]: 		java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
[09:00:06 ERROR]: ------------------------------
[09:00:06 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[09:00:06 ERROR]: ------------------------------
[09:00:07 WARN]: [ReallyFakePlayers] Fake player Lyndel disconnected with an error!
io.netty.channel.ConnectTimeoutException: connection timed out: /8.8.8.8:25565
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

[09:00:29 ERROR]: [ReallyFakePlayers] Fake player Lyndel doesn't seem to show any life signs after ~30 seconds, meaning he didn't join/quit correctly! Aborting!
</p>
</details>

**Comment by marlester-dev** [comment]
Sorry I have no idea what happened so I will close this issue
