### ISSUE TITLE
Fake players can't connect

### ISSUE THREAD

**Issue by J6833** [marlester-dev/ReallyFakePlayers#13]
I'm getting this error when a fake player tries to join the server:

```
[06:17:22] [Server thread/ERROR]: [ReallyFakePlayers] Fake player Gelais doesn't seem to show any life signs after ~30 seconds, meaning he didn't join/quit correctly! Aborting!
[06:17:22] [Server thread/INFO]: Gelais (/127.0.0.1:55099) lost connection: Disconnected
[06:18:02] [Server thread/INFO]: Added fake players number 1.
[06:18:20] [Server thread/INFO]: There are 0 of a max of 60 fake players online:
[06:18:22] [Server thread/ERROR]: [ReallyFakePlayers] Fake player Rodrigus doesn't seem to show any life signs after ~30 seconds, meaning he didn't join/quit correctly! Aborting!
[06:18:22] [Server thread/INFO]: Rodrigus (/127.0.0.1:34563) lost connection: Disconnected
```
Here is my config: [config.txt](https://github.com/marlester-dev/ReallyFakePlayers/files/14076341/config.txt)

**Comment by marlester-dev** [comment]
Hello, there should be more errors, check and send all errors and what happened 30 seconds before

**Comment by mrsbling** [comment]
mine is doing the same

[13:46:53 ERROR]: [ReallyFakePlayers] Fake player Sachiko doesn't seem to show any life signs after ~30 seconds, meaning he didn't join/quit correctly! Aborting!
[13:47:58 WARN]: [ReallyFakePlayers] Fake player Debbi disconnected with an error!
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:25421
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
        at io.netty.channel.unix.Errors.newConnectException0(Errors.java:166) ~[netty-transport-native-unix-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131) ~[netty-transport-native-unix-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.unix.Socket.finishConnect(Socket.java:359) ~[netty-transport-native-unix-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by marlester-dev** [comment]
likely falls under the same umbrella as #23
