### ISSUE TITLE
error in console, the jar does not load

### ISSUE THREAD

**Issue by ElEspix** [marlester-dev/ReallyFakePlayers#19]
I have version 1.20.4 of paper and I already have the miniplaceholders installed, which is working, but the fake players plugin throws an error

[20:09:00 ERROR]: [DirectoryProviderSource] Error preparing plugin context: Directory 'plugins/ReallyFakePlayers-3.0.3.jar' failed to update!
java.lang.RuntimeException: Directory 'plugins/ReallyFakePlayers-3.0.3.jar' failed to update!
at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:51) ~[paper-1.20.4.jar:git-Paper-435]
at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$prepareContext$1(DirectoryProviderSource.java:33) ~[paper-1.20.4.jar:git-Paper-435]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.walkFiles(DirectoryProviderSource.java:59) ~[paper-1.20.4.jar:git-Paper-435]
at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:31) ~[paper-1.20.4.jar:git-Paper-435]
at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[paper-1.20.4.jar:git-Paper-435]
at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.20.4.jar:git-Paper-435]
at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:101) ~[paper-1.20.4.jar:git-Paper-435]
at net.minecraft.server.Main.main(Main.java:131) ~[paper-1.20.4.jar:git-Paper-435]
at org.bukkit.craftbukkit.Main.main(Main.java:326) ~[paper-1.20.4.jar:git-Paper-435]
at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: org.bukkit.plugin.InvalidPluginException: java.util.zip.ZipException: zip END header not found
at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:109) ~[paper-1.20.4.jar:git-Paper-435]
at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:49) ~[paper-1.20.4.jar:git-Paper-435]
... 21 more
Caused by: java.util.zip.ZipException: zip END header not found
at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1633) ~[?:?]
at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1641) ~[?:?]
at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1479) ~[?:?]
at java.util.zip.ZipFile$Source.get(ZipFile.java:1441) ~[?:?]
at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718) ~[?:?]
at java.util.zip.ZipFile.<init>(ZipFile.java:252) ~[?:?]
at java.util.zip.ZipFile.<init>(ZipFile.java:181) ~[?:?]
at java.util.jar.JarFile.<init>(JarFile.java:346) ~[?:?]
at java.util.jar.JarFile.<init>(JarFile.java:317) ~[?:?]
at java.util.jar.JarFile.<init>(JarFile.java:283) ~[?:?]
at io.papermc.paper.plugin.provider.source.FileProviderSource.getPluginName(FileProviderSource.java:115) ~[paper-1.20.4.jar:git-Paper-435]
at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:90) ~[paper-1.20.4.jar:git-Paper-435]
at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:49) ~[paper-1.20.4.jar:git-Paper-435]
... 21 more

**Comment by ElEspix** [comment]
I have version 3.0.3 installed, but I also tried version 3.0.4 and it gave me the same error

**Comment by ElEspix** [comment]
SOLVED, thank you very much, excellent plugin

**Comment by ElEspix** [comment]
SOLVED, thank you very much, excellent plugin
