### ISSUE TITLE
Bug Report: Not sure what happen?

### ISSUE THREAD

**Issue by BruhItsMarc** [marlester-dev/ReallyFakePlayers#3]
### Describe the bug.

[21:55:11 ERROR]: Error occurred while enabling ReallyFakePlayers v1.1.0.4-1.19.4 (Is it up to date?)

### What happened?

It didnt load up.

### What version of the plugin are you using?

1.19.4

### What Minecraft version does your server use?

purpur-1.19.2-1825

### Relevant log output or error stacktrace.

```shell
[21:55:11 ERROR]: Error occurred while enabling ReallyFakePlayers v1.1.0.4-1.19.4 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R3/CraftServer
        at net.marlester.rfp.managers.FakePlayerManager.<init>(FakePlayerManager.java:50) ~[ReallyFakePlayers-1.1.0.4-1.19.4.jar:?]
        at net.marlester.rfp.TitanBoxRFP.onEnable(TitanBoxRFP.java:50) ~[ReallyFakePlayers-1.1.0.4-1.19.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1825]        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_19_R3.CraftServer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
[21:55:11 INFO]: [ReallyFakePlayers] Disabling ReallyFakePlayers v1.1.0.4-1.19.4
[21:55:11 ERROR]: Error occurred while disabling ReallyFakePlayers v1.1.0.4-1.19.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.marlester.rfp.managers.FakePlayerManager.removeAll()" because "net.marlester.rfp.TitanBoxRFP.fakePlayerManager" is null
        at net.marlester.rfp.TitanBoxRFP.onDisable(TitanBoxRFP.java:420) ~[ReallyFakePlayers-1.1.0.4-1.19.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:402) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:585) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:377) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1825]        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Did you make any (noteworthy) changes to configuration?

nope

### Checklist.

- [X] I am running latest version of the plugin.
- [X] I confirm that there are no similar issues.
- [ ] I ticked all of the boxes without actually reading them.
- [X] I am not trying to run the plugin on an unsupported server version / platform.

**Comment by BruhItsMarc** [comment]
im on 1.19.4 and up
