### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HEMO313** [marlester-dev/ReallyFakePlayers#32]
[18:24:38 ERROR]: Error occurred while enabling ReallyFakePlayers v3.0.9 (Is it up to date?)
javassist.CannotCompileException: [source error] no such class: packet
        at javassist.expr.MethodCall.replace(MethodCall.java:257) ~[?:?]
        at me.marlester.rfp.bytecodeedit.LoginListenerEditor$1.edit(LoginListenerEditor.java:111) ~[ReallyFakePlayers-3.0.9.jar:?]
        at javassist.expr.ExprEditor.loopBody(ExprEditor.java:197) ~[?:?]
        at javassist.expr.ExprEditor.doit(ExprEditor.java:96) ~[?:?]
        at javassist.CtBehavior.instrument(CtBehavior.java:744) ~[?:?]
        at me.marlester.rfp.bytecodeedit.LoginListenerEditor.startEditing(LoginListenerEditor.java:69) ~[ReallyFakePlayers-3.0.9.jar:?]
        at me.marlester.rfp.bytecodeedit.BytecodeEditingRegistrar.registerBytecodeEditions(BytecodeEditingRegistrar.java:42) ~[ReallyFakePlayers-3.0.9.jar:?]
        at me.marlester.rfp.ReallyFakePlayers.onEnable(ReallyFakePlayers.java:69) ~[ReallyFakePlayers-3.0.9.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[pufferfishplus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin() ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin() ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfishplus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin() ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins() ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: javassist.compiler.CompileError: no such class: packet
        at javassist.compiler.MemberResolver.searchImports(MemberResolver.java:486) ~[?:?]
        at javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:429) ~[?:?]
        at javassist.compiler.MemberResolver.lookupClassByJvmName(MemberResolver.java:336) ~[?:?]
        at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:711) ~[?:?]
        at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170) ~[?:?]
        at javassist.compiler.ast.CallExpr.accept(CallExpr.java:49) ~[?:?]
        at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266) ~[?:?]
        at javassist.compiler.CodeGen.atDeclarator(CodeGen.java:819) ~[?:?]
        at javassist.compiler.ast.Declarator.accept(Declarator.java:103) ~[?:?]
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381) ~[?:?]
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[?:?]
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381) ~[?:?]
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[?:?]
        at javassist.compiler.MemberCodeGen.atTryStmnt(MemberCodeGen.java:234) ~[?:?]
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:397) ~[?:?]
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[?:?]
        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381) ~[?:?]
        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[?:?]
        at javassist.compiler.Javac.compileStmnt(Javac.java:578) ~[?:?]
        at javassist.expr.MethodCall.replace(MethodCall.java:251) ~[?:?]
        ... 19 more
[18:24:38 INFO]: [ReallyFakePlayers] Disabling ReallyFakePlayers v3.0.9

**Comment by marlester-dev** [comment]
Hello HEMO313 👋,
it seems like you are using Minecraft version 1.20.4.
For this version you would need to download the plugin version 3.0.6, as 3.0.9 is for 1.20.6.
Cheers
