### ISSUE TITLE
The plugin for version 1.20.4 cannot download dependencies.

### ISSUE THREAD

**Issue by xinge4088** [marlester-dev/ReallyFakePlayers#44]
09:58:30 ERROR]: [DirectoryProviderSource] Error loading plugin: Error resolving libraries
io.papermc.paper.plugin.loader.library.LibraryLoadingException: Error resolving libraries
        at io.papermc.paper.plugin.loader.library.impl.MavenLibraryResolver.register(MavenLibraryResolver.java:125) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.loader.PaperClasspathBuilder.buildClassLoader(PaperClasspathBuilder.java:44) ~[paper-1.20.4.jar:?]
        at io.papermc.paper.plugin.provider.type.paper.PaperPluginProviderFactory.build(PaperPluginProviderFactory.java:44) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.provider.type.paper.PaperPluginProviderFactory.build(PaperPluginProviderFactory.java:23) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:74) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:47) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:101) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.Main.main(Main.java:120) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.Main.main(Main.java:326) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: net.kyori:adventure-text-serializer-gson:jar:4.15.0-20231207.074016-23 (absent), net.kyori:adventure-text-serializer-json-legacy-impl:jar:4.15.0-20231207.074016-23 (absent): Could not find artifact net.kyori:adventure-text-serializer-gson:jar:4.15.0-20231207.074016-23 in MavenRepo (https://repo.maven.apache.org/maven2/)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:365) ~[maven-resolver-impl-1.9.18.jar:1.9.18]
        at io.papermc.paper.plugin.loader.library.impl.MavenLibraryResolver.register(MavenLibraryResolver.java:123) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 13 more

**Comment by marlester-dev** [comment]
Hello, sorry, but because of the outdated dependencies I decided, that 1.20.4 support should be dropped. Please update to 1.20.6 or 1.21 asap.
