### ISSUE TITLE
Bug Report: 1.19.4 Console gets spammed with errors and then server crashes

### ISSUE THREAD

**Issue by Dragonsoturi** [marlester-dev/ReallyFakePlayers#9]
### Describe the bug.

Console gets spammed with errors and then server crashes

### What happened?

I am trying to use the 1.19.4 version on my server but it keeps crashing the server during the boot process. initially I had a bug due to luck perms being out of date, but now its doing the crashing issue. 

I saw in other reported issues that there is an unofficial release / rewrite. any way that I could get that?

### What version of the plugin are you using?

1.1.0.4

### What Minecraft version does your server use?

1.19.4

### Relevant log output or error stacktrace.

```shell
15.12 10:21:39 [Server] WARN java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
15.12 10:21:39 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
15.12 10:21:39 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
15.12 10:21:39 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
15.12 10:21:39 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
15.12 10:21:39 [Server] WARN at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
15.12 10:21:39 [Server] WARN at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
15.12 10:21:39 [Server] WARN at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
15.12 10:21:39 [Server] WARN at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
15.12 10:21:39 [Server] WARN at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
15.12 10:21:39 [Server] WARN Caused by: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
15.12 10:21:39 [Server] WARN at java.base/java.lang.Thread.start0(Native Method)
15.12 10:21:39 [Server] WARN at java.base/java.lang.Thread.start(Thread.java:809)
15.12 10:21:39 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945)
15.12 10:21:39 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1353)
15.12 10:21:39 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782)
15.12 10:21:39 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005)
15.12 10:21:39 [Server] WARN at PhoenixLobby-1.3.2.jar//com.phoenixplugins.phoenixlobby.spigot.lib.common.services.services.database.context.DatabaseRepository.insertLater(DatabaseRepository.java:451)
15.12 10:21:39 [Server] WARN at PhoenixLobby-1.3.2.jar//com.phoenixplugins.phoenixlobby.spigot.managers.PlayersManager.getPlayerFromDatabase(PlayersManager.java:86)
15.12 10:21:39 [Server] WARN at PhoenixLobby-1.3.2.jar//com.phoenixplugins.phoenixlobby.spigot.managers.PlayersManager.lambda$fetchAsyncAndCache$2(PlayersManager.java:175)
15.12 10:21:39 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
15.12 10:21:39 [Server] WARN ... 6 more
15.12 10:21:49 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-519 (MC: 1.19.4) ---
15.12 10:21:49 [Server] ERROR The server has not responded for 10 seconds! Creating thread dump
15.12 10:21:49 [Server] ERROR ------------------------------
15.12 10:21:49 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
15.12 10:21:49 [Server] ERROR ------------------------------
15.12 10:21:49 [Server] ERROR Current Thread: Server thread
15.12 10:21:49 [Server] ERROR PID: 23 | Suspended: false | Native: false | State: WAITING
15.12 10:21:49 [Server] ERROR Stack:
15.12 10:21:49 [Server] ERROR java.base@17.0.9/jdk.internal.misc.Unsafe.park(Native Method)
15.12 10:21:49 [Server] ERROR java.base@17.0.9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
15.12 10:21:49 [Server] ERROR java.base@17.0.9/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
15.12 10:21:49 [Server] ERROR java.base@17.0.9/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
15.12 10:21:49 [Server] ERROR java.base@17.0.9/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
15.12 10:21:49 [Server] ERROR java.base@17.0.9/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
15.12 10:21:49 [Server] ERROR java.base@17.0.9/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
15.12 10:21:49 [Server] ERROR PhoenixLobby-1.3.2.jar//com.phoenixplugins.phoenixlobby.spigot.managers.PlayersManager.fetchPlayerDataSync(PlayersManager.java:120)
15.12 10:21:49 [Server] ERROR PhoenixLobby-1.3.2.jar//com.phoenixplugins.phoenixlobby.spigot.managers.PlayersManager.fetchPlayerDataSync(PlayersManager.java:115)
15.12 10:21:49 [Server] ERROR PhoenixLobby-1.3.2.jar//com.phoenixplugins.phoenixlobby.spigot.managers.modules.JoinModule.setupInventoryItems(JoinModule.java:529)
15.12 10:21:49 [Server] ERROR PhoenixLobby-1.3.2.jar//com.phoenixplugins.phoenixlobby.spigot.managers.modules.JoinModule.lambda$onPlayerChangedWorld$3(JoinModule.java:263)
15.12 10:21:49 [Server] ERROR PhoenixLobby-1.3.2.jar//com.phoenixplugins.phoenixlobby.spigot.managers.modules.JoinModule$$Lambda$11177/0x00007f6dae3c21e8.run(Unknown Source)
15.12 10:21:49 [Server] ERROR org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
15.12 10:21:49 [Server] ERROR org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
15.12 10:21:49 [Server] ERROR net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483)
15.12 10:21:49 [Server] ERROR net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447)
15.12 10:21:49 [Server] ERROR net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397)
15.12 10:21:49 [Server] ERROR net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174)
15.12 10:21:49 [Server] ERROR net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
15.12 10:21:49 [Server] ERROR net.minecraft.server.MinecraftServer$$Lambda$4649/0x00007f6dac9ed1f0.run(Unknown Source)
15.12 10:21:49 [Server] ERROR java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
15.12 10:21:49 [Server] ERROR ------------------------------
15.12 10:21:49 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
15.12 10:21:49 [Server] ERROR ------------------------------
15.12 10:21:54 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-519 (MC: 1.19.4) ---
15.12 10:21:54 [Server] ERROR The server has not responded for 15 seconds! Creating thread dump
15.12 10:21:54 [Server] ERROR ------------------------------
15.12 10:21:54 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
15.12 10:21:54 [Server] ERROR ------------------------------
```

### Did you make any (noteworthy) changes to configuration?

Nothing crazy. tried on default settings, didnt work, and tried many times after tweaking settings

### Checklist.

- [X] I am running latest version of the plugin.
- [X] I confirm that there are no similar issues.
- [ ] I ticked all of the boxes without actually reading them.
- [X] I am not trying to run the plugin on an unsupported server version / platform.

**Comment by TheRealWren** [comment]
Yep, same for me. Server always crashes with this plugin.
